language: node_js
sudo: false
node_js:
- '6'
branches:
  only:
  - master
  - develop
  - "/v\\d+\\.\\d+\\.\\d+?.*/"
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=inc@2inc.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=inc@2inc.org
  - secure: kJS266orZqY/ClRbkj+WVrkaG3v/2k59ih+5D4V6vykb7kkBXoGm/INlVxoRk/1GpvysPlYAoS5/86lZh+0F3kFueVALRo0bgBbHXbBiupoGb0cy0LnJAfOyrDmX7B0TibwmHycmAaDWzfzJN/x3C+p1azEyZNpAQ4ctMSFXYdsimO4OVxzLWrT55N91YmgDGZhMMdn5n4cgRLFFMkDSdWqv5x2SybIsBuZQ3depLtLOzNNhSpjrmgsgida12ODZk0Lz7utwTflwLUuSpSCbbP0U+mj27BTKOJkJwhyUOYkRDj3fhxO5JTzrJGjSG19sOP1M9bJVFvqBxEJi3vqeGSHYdEwzwbFqkdJBdJzbdI51hSqz78QmGfPA3aBgnhd83BjENMFpvzrho3E2kBa4OOe3BiEPalx0ioR1Mj/ssUgxNKnB8ShPiJ7n9f3CG3+wxlVU6LdZ7pRoTfV0dlWc2RzS6tKqxCRk8zL31vkjGdOiINJHZ3PnU1A8HimHQ5q9FT/i5fdR6eCxQDFGB9NF5LCpFvzkQNjSm9WTsopctpH7Q2NXaHPMZFfgvzIgN/CIKGC6PvwWJcBxRdmNLYFAlUZ2dOBdV011JPQkcEpzRZwISNfhefrp1+CBnPq345kcc/8VLgvqFPrJxP7ko++IrwUdaP+vT2vxk3Q+QKWOTYU=
script:
- yarn run gulp build
before_deploy:
- yarn run gulp zip
deploy:
  provider: releases
  api_key:
    secure: A8qPo5Z1dJjkIFFUtTzOnzTwOXHKWy0TgZ8PTpty8tKAPtacjppFKmprCuOJdZzkfV9nd4Fp1/e0Fw9354Zz6g1rVxVj6Wvz40U89/PR7tahAi/V+qpRudoNltS1X1VJ435my60KBpDaMQGpftKWTjQ4V+JJCm4Nc4Nq6ZXzIQQ2T7gTsKp42XKo+mrx3LxkL22kNWY+IbG+saLPnck7CzD+Rn+CjIm6ZCly95tjMxsFHN5H3HFJtrm8WEsB3PzVnKS8v7mYds/n0iWaLVnn4pYedozbF5IyjW39QizFlbpKUrWDMj5Szl4b+21B+QPL+73xOeFg3PWdiuSKHgoDUPtcKwmBUqhK5jU1DbttvyUf+MAy7oRqrPUu/G15wnwgatPKdYvZqNGhZGbX1GutQ9GOOgNMuH4AiRtOSCKKp1QKn025rCA4ppQPk4/tWqgVfsRqjC1jtYWt303Qd3u1R9XPu8/mwa3qlCEAqknir0jXAO4bBFZkLf3pH6GxVacHcN10xFRjqg+ny1TUBRlhXgcqSWIT7MIsx+JFRv1+o/PV+91PP09+HQsoB+8W8zxcR4xIaTuQgg9qEGjT1PsaLcX/SxKvtnZBEB4w1DQd4hAr+CN6LYAPPsbVsx/dEr1VYc4nVsmPyeQ96EFMugy23w4SiWYvA3WCPaXYenXoEl0=
  file: basis.zip
  on:
    tags: true
    repo: getbasis/basis
